import "~/styles/globals.css";
import "@mantine/core/styles.css"

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";
import { MantineProvider, ColorSchemeScript, createTheme } from "@mantine/core";

export const metadata = {
  title: "Mantine + T3 Template",
  description: "Generated by create-t3-app, improved with mantine",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const theme = createTheme({
  /** Put your mantine theme override here */
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <TRPCReactProvider>
          <MantineProvider theme={theme}>
            {children}
          </MantineProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
